services:
  api:
    build: .
    command: >
      sh -c "gunicorn evolutiontransformer.api:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - worker
    env_file:
      - .env

  worker:
    build: .
    command: >
      sh -c "/usr/local/bin/celery -A evolutiontransformer.worker.celery_app worker --loglevel=info -c 1"
    env_file:
      - .env
